name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Grades
      id: grades
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Grades
        setup-command: pip install pytest
        command: pytest grading.py
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GRADES_RESULTS: "${{steps.grades.outputs.result}}"
      with:
        runners: grades
